### ISSUE TITLE
Make tickets for TODO's in code

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-hydra#47]
Either make tickets or remove each of the TODO's listed below (grep'ed on 12/4/12)
- [x] ./configure.yml:# TODO: it should work to default to all ec2hosts in this way:
- [x] ./README.md:4. TODO: deploy your capistrano project to your vagrant box. Haven't tried this yet.
- [x] ./roles/app-config/tasks/systems.yml:#TODO: manage env variables for this separately
  ./roles/ec2/tasks/ec2_crons.yml:# TODO
- [x] ./roles/hydra-stack/install/tasks/fedora.yml:# TODO: make Java options configurable at the time of the ansible run
- [x] ./roles/hydra-stack/install/tasks/fedora.yml:# TODO: make this a service called from main.yml

**Comment by hackartisan** [comment]
We believe the ones here are done:
https://github.com/curationexperts/ansible-hydra/blob/master/roles/ec2/tasks/ec2_crons.yml#L3

**Comment by acozine** [comment]
how to deploy your capistrano project to your vagrant box: #75 
configuring java options: #72 
calling the restart tomcat service task from main.yml: #73

**Comment by acozine** [comment]
Goal of the TODO from configure.yml was achieved in 9d56361c2a4ded1235e6c915980f3e1b776d1fb1 - as soon as I remove the comment from configure, I will close this ticket.

**Comment by acozine** [comment]
Closed by 29c260acd1c0c9a9c5351c805a693a309e511801
